Change checking time limit method. Add condition if no tests are found. Change a bit error messages.

diff --git a/oitestool b/oitestool
--- a/oitestool
+++ b/oitestool
@@ -9,7 +9,7 @@ LIGHTBLUE="\e[1;34m"
 YELLOW="\e[1;33m"
 
 help() {
-  printf "%s\n" "${0##*/} [OPTIONS] taskname"
+  printf "%s\n" "$(basename $0) [OPTIONS] taskname"
   printf "%s\n"   "Options:"
   printf " %s\t%s\n" "-h, --help        " "Show this help"
   printf " %s\t%s\n" "-b, --binary      " "Test binary file without compiling source"
@@ -25,7 +25,6 @@ OUTPUT_DIR=""
 BINARY=false
 GENERATE_OUT=false
 TIME_LIMIT="unlimited"
-ULIMIT_T=$(ulimit -t)
 MEMORY_LIMIT="unlimited"
 task=""
 
@@ -65,7 +64,7 @@ while [ "$1" != "" ]; do
       ;;
     "--timeout"|"-t")
       shift
-      TIME_LIMIT"$1"
+      TIME_LIMIT="$1"
       ;;
     "--memory-limit"|"-m")
       shift
@@ -79,13 +78,10 @@ while [ "$1" != "" ]; do
 done
 
 if [ "${task}" = "" ]; then
-  printf "%s\n" "Task name missing"
+  printf "%s\n" "! Error: task name missing"
   exit 1
 fi
 
-if [ "${INPUT_DIR}" = "" ]; then
-  INPUT_DIR="./"
-fi
 if [ "${OUTPUT_DIR}" = "" ]; then
   OUTPUT_DIR="${INPUT_DIR}"
 fi
@@ -94,11 +90,11 @@ if $BINARY ; then
   if [ -f "${task}" ]; then
     printf "%s\n" "Testing earlier compiled task..."
   else
-    printf "%s\n" "${task} - task binary file does not exist"
+    printf "%s\n" "! Error: ${task} - task binary does not exist or is not executable"
     exit 1
   fi
 elif [ ! -f "${task}.cpp" ]; then
-  printf "%s\n" "${task}.cpp - task source file does not exist"
+  printf "%s\n" "! Error: ${task}.cpp - task source does not exist"
   exit 1
 elif [ ! -f Makefile ]; then
   g++ -Wall -O2 -static -std=gnu++0x ${task}.cpp -o ${task}
@@ -118,23 +114,28 @@ COUNT_MEM=0
 COUNT_RTE=0
 COUNT_CANCELLED=0
 COUNT_UNKNOWN=0
+TIME_LIMIT_CMD=""
+if [ "${TIME_LIMIT}" != "unlimited" ]; then
+  TIME_LIMIT_CMD="timeout $TIME_LIMIT"
+fi
+
+tests=($INPUT_DIR*.in)
+
+if [ ${tests[0]} == "$INPUT_DIR*.in" ]; then
+  printf "%s\n" "! Error: no tests found"
+  exit 1
+fi
 
 printf "${WHITE}%s\n" "------------------- TESTING $(basename $task) ---------------------"
-
-for test in ${INPUT_DIR}*.in; do
+for test in "${tests[@]}"; do
 
   test=${test%%.in}
   test=$(basename $test)
 
   printf "${WHITE}%s" "${test} "
-
   
-  if [ "${TIME_LIMIT}" != "unlimited" ]; then
-   ulimit -St $TIME_LIMIT
-  fi
-  /usr/bin/time -f "%E %M" -o time.tmp sh -c "./${task} < ${INPUT_DIR}${test}.in > out.tmp 2> /dev/null" 2> /dev/null
+  /usr/bin/time -f "%E %M" -o time.tmp sh -c "${TIME_LIMIT_CMD} ./${task} < ${INPUT_DIR}${test}.in > out.tmp 2> /dev/null" 2> /dev/null
   EXIT_CODE=$?
-  ulimit -St $ULIMIT_T
 
   printf "%s\n" "$(sed '/Command/d' time.tmp)" > time.tmp
 
@@ -159,21 +160,24 @@ for test in ${INPUT_DIR}*.in; do
     "124")
       IS_TLE=true
       ;;
-    "130"|"2")
+    "130")
       ((++COUNT_CANCELLED))
       printf "${LIGHTRED}%s\n" "CANCELLED (press Ctrl-| to interrupt whole script)" 
       continue
       ;;
-    "131"|"3")
+    "131")
+      printf "%s\n" "Script interrupted"
       exit 131
       ;;
-    "136"|"8")
+    "136")
       ((++COUNT_RTE))
       printf "${LIGHTRED}%s\n" "FAIL (floating point exception - division by 0??)"
+      continue
       ;;
-    "139|11")
+    "139")
       ((++COUNT_RTE))
-      printf "${LIGHTRED}%s\n" "FAIL (out of range invocation??)"
+      printf "${LIGHTRED}%s\n" "FAIL (exit code $EXIT_CODE - out of range invocation??)"
+      continue
       ;;
     *)
       ((++COUNT_RTE))
@@ -214,6 +218,9 @@ done
 
 printf "${WHITE}%s\n"        "--------------------- RESULTS -----------------------"
 if  $GENERATE_OUT ; then
+  if [ $OUTPUT_DIR  = "" ]; then
+    OUTPUT_DIR="current directory"
+  fi
   printf "${YELLOW}%s\n"     "${COUNT_GENERATED} outputs generated into ${OUTPUT_DIR}"
 else
   printf "${LIGHTGREEN}%s\n" "OK:                                              ${COUNT_OK}"
