Change moethod of displaying errors

diff --git a/oitestool b/oitestool
--- a/oitestool
+++ b/oitestool
@@ -1,6 +1,7 @@
 #!/bin/bash
 NORMAL="\033[0m"
 WHITE="\033[1;37m"
+RED="\033[0;31m"
 LIGHTRED="\033[1;31m"
 LIGHTGREEN="\033[1;32m"
 LIGHTCYAN="\e[1;36m"
@@ -13,11 +14,16 @@ help() {
   printf "%s\n"   "Options:"
   printf " %s\t%s\n" "-h, --help        " "Show this help"
   printf " %s\t%s\n" "-b, --binary      " "Test binary file without compiling source"
-  printf " %s\t%s\n" "-i, --input-dir   " "Path to folder with input data (also answers dir unless specified"
-  printf " %s\t%s\n" "-o, --output-dir  " "Path to folder with answers"
+  printf " %s\t%s\n" "-i, --input-dir   " "Path to folder with input data (also output-dir unless specified)"
+  printf " %s\t%s\n" "-o, --output-dir  " "Path to folder with output"
   printf " %s\t%s\n" "-g, --generate-out" "Instead checking answers, generate them"
   printf " %s\t%s\n" "-t, --timeout"      "Set timeout in seconds, default: unlimited"
   printf " %s\t%s\n" "-m, --memory-limit" "Set memory limit, default: unlimited"
+}
+
+exit_error() {
+  printf "${RED}%s\n" "! Error: $1"
+  exit 1
 }
 
 INPUT_DIR=""
@@ -41,8 +47,7 @@ while [ "$1" != "" ]; do
       shift
       INPUT_DIR="$1"
       if [ ! -d "${INPUT_DIR}" ]; then
-        printf "%s\n" "${INPUT_DIR} - input directory does not exist"
-        exit 1
+        exit_error "${INPUT_DIR} - input directory does not exist"
       fi
       if [ "${INPUT_DIR##*/}" != "" ]; then
         INPUT_DIR="${INPUT_DIR}/"
@@ -52,8 +57,7 @@ while [ "$1" != "" ]; do
       shift
       OUTPUT_DIR="$1"
       if [ ! -d "${OUTPUT_DIR}" ]; then
-        printf "%s\n" "${OUTPUT_DIR} - output directory does not exist"
-        exit 1
+        exit_error "${OUTPUT_DIR} - output directory does not exist"
       fi
       if [ "${OUTPUT_DIR##*/}" != "" ]; then
         OUTPUT_DIR="${OUTPUT_DIR}/"
@@ -78,8 +82,7 @@ while [ "$1" != "" ]; do
 done
 
 if [ "${task}" = "" ]; then
-  printf "%s\n" "! Error: task name missing"
-  exit 1
+  exit_error "task name missing"
 fi
 
 if [ "${OUTPUT_DIR}" = "" ]; then
@@ -90,12 +93,10 @@ if $BINARY ; then
   if [ -f "${task}" ]; then
     printf "%s\n" "Testing earlier compiled task..."
   else
-    printf "%s\n" "! Error: ${task} - task binary does not exist or is not executable"
-    exit 1
+    exit_error "${task} - task binary does not exist or is not executable"
   fi
 elif [ ! -f "${task}.cpp" ]; then
-  printf "%s\n" "! Error: ${task}.cpp - task source does not exist"
-  exit 1
+  exit_error "${task}.cpp - task source does not exist"
 elif [ ! -f Makefile ]; then
   g++ -Wall -O2 -static -std=gnu++0x ${task}.cpp -o ${task}
 else
@@ -122,8 +123,7 @@ fi
 tests=($INPUT_DIR*.in)
 
 if [ ${tests[0]} == "$INPUT_DIR*.in" ]; then
-  printf "%s\n" "! Error: no tests found"
-  exit 1
+  exit_error "no tests found"
 fi
 
 printf "${WHITE}%s\n" "------------------- TESTING $(basename $task) ---------------------"
@@ -166,7 +166,7 @@ for test in "${tests[@]}"; do
       continue
       ;;
     "131")
-      printf "%s\n" "Script interrupted"
+      printf "${RED}%s\n" "Script interrupted"
       exit 131
       ;;
     "136")
